[tool.poetry]
name = "auto-clicker"
version = "0.0.1"
description = ""
authors = ["d.finko <d.finko@x5.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
pynput = "^1.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
